# -*- coding: utf-8 -*-
"""P1_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d40B-PTsZ_X4tqkwpI_hMJeeTZrjkwIq
"""

def can_piece_move(role, x1, y1, x2, y2):
    # 條件1：不能停留在原地
    if x1 == x2 and y1 == y2:
        return "No"

    dx, dy = abs(x2 - x1), abs(y2 - y1)

    # 根據角色判斷規則
    if role == "國王":
        # 國王：移動一格，前後左右或斜向
        if dx <= 1 and dy <= 1:
            return "Yes"

    elif role == "皇后":
        # 皇后：直線或斜線不限距離
        if dx == dy or x1 == x2 or y1 == y2:
            return "Yes"

    elif role == "主教":
        # 主教：斜線不限距離
        if dx == dy:
            return "Yes"

    elif role == "城堡":
        # 城堡：直線不限距離
        if x1 == x2 or y1 == y2:
            return "Yes"

    elif role == "騎士":
        # 騎士：L 形移動
        if (dx == 2 and dy == 1) or (dx == 1 and dy == 2):
            return "Yes"

    elif role == "士兵":
        # 士兵：只考慮基本前進規則（忽略吃子與升變）
        # 僅允許直線前進一格
        if x1 == x2 and y2 - y1 == 1:
            return "Yes"

    # 若不符合任何規則，回傳 "No"
    return "No"


# 測試輸入
role = input()  # 棋子角色
x1, y1 = map(int, input().split())  # 起始座標
x2, y2 = map(int, input().split())  # 目標座標

# 輸出結果
print(can_piece_move(role, x1, y1, x2, y2))